name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.5
    - name: Cache Gems
      id: cache-gems
      uses: actions/cache@v1
      with:
        path: vendor/ruby
        key: ${{ runner.os }}-gems
    - name: Install Gems
      if: steps.cache-gems.outputs.cache-hit != 'true'
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path=vendor/ruby
    - name: Build and test with RSpec
      run: bundle exec rspec spec
